### ISSUE TITLE
Request 'X-Authorization' as allowed header in a CORS preflight check

### ISSUE THREAD

**Issue by rhuss** [hawtio/hawtio-jmx#10]
In order to be able to use the new header `X-Authorization` header in a CORS request it must be white listed by a preflight CORS request as described [here](http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0). I wonder, why `Authorization` works because this is also not a [simple header](http://www.w3.org/TR/cors/#simple-header) and hence must be white listed, too.

@cmoulliard ran into this issue first:

![image](https://cloud.githubusercontent.com/assets/99080/9847448/23b5b40c-5ad9-11e5-804e-60b1a1ad3ddb.png)

**Comment by gashcrumb** [comment]
Ah, this also requires the responding entity to reply back to the preflight request with `Access-Control-Allow-Headers` set to the same headers also to work -> http://stackoverflow.com/questions/8685678/cors-how-do-preflight-an-httprequest, wonder that might get broken by the proxy as well...  `<sigh>`

**Comment by rhuss** [comment]
Jolokia is very liberal ;-) and always returns all requested headers but you are right, might be that the proxy is filtering this, too. I will check that ...

**Comment by rhuss** [comment]
An option would be to put it into a 'simple header' but that definitely would be a dirty, dirty hack.

**Comment by gashcrumb** [comment]
Yeah, wonder, maybe we can just get the proxy to not overwrite that, as that probably can break other apps too.

**Comment by rhuss** [comment]
Well, we are probably [doomed](https://github.com/openshift/origin/blob/945fb793cf68ba3836a75239b14b05fcbe44427a/pkg/util/httpproxy/upgradeawareproxy.go#L251-L256) ;-(

'will now check, to which header the proxy itself sends back on a preflight check ...

**Comment by gashcrumb** [comment]
`>ack<`

**Comment by rhuss** [comment]
AFAIK the proxy is meant to filter all backend CORS headers ;-(

**Comment by rhuss** [comment]
@dhirajsb we have a serious issue now, because the proxy filters the CORS respond for allowed headers (in fact it probably even answers the CORS preflight check on its own). That means we can't use  a custom header to transport the toke across the proxy and unforturnately there is currently no good solution. 

I suggest we continue the discussion over within the original issue https://github.com/openshift/origin/issues/4497

**Comment by rhuss** [comment]
The proxy answers to the preflight check itself and returns the following allowed headers:

```
Content-Type
Content-Length
Accept-Encoding
X-CSRF-Token
Authorization
X-Requested-With
If-Modified-Since
```

(where `Content-Type`  wouldn't be needed because its a [simple header](http://www.w3.org/TR/cors/#simple-header))

**Comment by rhuss** [comment]
As mentioned on IRC the current trust relation between hawt.io and Jolokia is very weak and is only based on the availability of a certain port (8778). So even the solution with passing the token is not really secure. The only secure way would be the passing of a token from proxy to Jolokia which can be verified without a querying without a central service (i.e. with a signature a la json web token, the public key could be injected to every pod by OpenShift).

**Comment by davsclaus** [comment]
Is there more work to this ticket or can it be closed?

**Comment by abkieling** [comment]
Is there any work left in this ticket?

**Comment by gashcrumb** [comment]
Actually no, we decided to ditch this approach, so let's go ahead and close it.
