### ISSUE TITLE
Stop injecting 'workspace' in the hawtio-ui tree component

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-jmx#21]
The `workspace` resource from hawtio-jmx is being injected in the hawtio-ui tree component with the intention of being notified about node selections. The correct way for hawtio-jmx to be notified about node selections is via the `onSelect` callback.

**Comment by abkieling** [comment]
I'll try to fix this one.

**Comment by astefanutti** [comment]
Should be fixed by now.
