### ISSUE TITLE
JMX Connection Warning Modal Malformed

### ISSUE THREAD

**Issue by jbornemann** [hawtio/hawtio-jmx#23]
Not sure if this is the appropriate project to log this issue or not, because the CSS interfering may be elsewhere (like hawtio/openshift-jvm)

Modal style is malformed:

<img width="1385" alt="openshift-jvm" src="https://cloud.githubusercontent.com/assets/4540994/26503102/6aa489d4-420d-11e7-90be-a524664212d2.png">

happens during unauthorized requests..

<img width="1378" alt="openshift-jvm 2" src="https://cloud.githubusercontent.com/assets/4540994/26503111/717a0144-420d-11e7-889b-29765a0fd2ac.png">

Versions affected:
origin v1.5.0+031cbe4
repro chrome 58.0.3029.110

Repro steps:
1.) Open up two tabs via "Open Java Console" on a pod that exposes a jolokia port
2.) In first tab, log out
3.) Reload 2nd tab to get pod request authorization to fail

**Comment by abkieling** [comment]
@jbornemann I'm sorry for the late reply. Is this issue still happening?

**Comment by jbornemann** [comment]
This was fixed in later versions. Thanks @akieling
