### ISSUE TITLE
JVM plugin - Connect redirects to root context '/?con=<name>'

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-jmx#24]
It causes `404` error (or something else) when hawtio is deployed on other than the root context (e.g. `/hawtio`).

**Comment by skarsaune** [comment]
Have not seen this before. Do we have concrete steps to reproduce?

**Comment by skarsaune** [comment]
Ah, this is 2.0? The danger when replying from my phone on the train.
Sorry, disregard my comment.

**Comment by tadayosi** [comment]
You can see this by running `hawtio-app-2.0-SNAPSHOT.jar` and trying to connect to another Jolokia endpoint. You'll then see `HTTP ERROR 404`.

**Comment by tadayosi** [comment]
@skarsaune no worries :-)  Thank you for watching the hawtio issues.

**Comment by tadayosi** [comment]
For the record: https://issues.jboss.org/browse/ENTESB-7274

**Comment by tadayosi** [comment]
Already fixed in the recent codebase.
