### ISSUE TITLE
JMX plugin - JMX tree not visible initially after page reload

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-jmx#30]
After my work on RBAC support, now the JMX tree is not visible immediately after reloading the page. Moving tabs around you can still see the JMX tree showing up.

**Comment by abkieling** [comment]
@tadayosi please ask @astefanutti to help you with this one. He's done most of the latest work on the tree.

**Comment by abkieling** [comment]
@astefanutti I tried to fix this bug a while ago but gave up after a couple of hours. It would be great if you could have a look when you can.

**Comment by astefanutti** [comment]
@akieling sure, let me have a look ASAP.

**Comment by abkieling** [comment]
@astefanutti Did you manage to reproduce this issue?

**Comment by astefanutti** [comment]
@akieling haven't look at it yet. Will do ASAP.

**Comment by abkieling** [comment]
@astefanutti I was able to reproduce this issue in the Camel tree but not in the JMX tree.

**Comment by astefanutti** [comment]
Relates to hawtio/hawtio-integration#50.

**Comment by astefanutti** [comment]
@akieling I can reproduce with the Camel tree but not the JMX one. @tadayosi could you confirm?

**Comment by tadayosi** [comment]
I reproduce it with hawtio-jmx using Chrome. Note you need to reload the page after viewing the JMX tab.

<img width="991" alt="screen shot 2018-01-24 at 13 10 21" src="https://user-images.githubusercontent.com/156692/35314215-05344926-0108-11e8-9364-530f60e1f506.png">
