### ISSUE TITLE
Diagnostics - Hotspot Diagnostics: use pfTableView with toolbar

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-jmx#39]
Use the pfTableView with an integrated toolbar.
https://www.patternfly.org/angular-patternfly/#/api/patternfly.table.component:pfTableView%20-%20with%20Toolbar

**Comment by skarsaune** [comment]
FYI: I have failed to simplify this form a couple of times in the past. The main issue was that all the options can be retrieved as an attribute, but update is done via setVMOption(String, String). Hopefully there is a better solution than I was able to come up with.

**Comment by abkieling** [comment]
Improved the UI using a simple PatternFly table. We can change it to an Angular PatternFly pfTableView if we feel the need to have multiple filters and sorting on all columns.
