### ISSUE TITLE
Connect plugin - Update Instructions

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-jmx#40]
Some parts (like that mentioning Fabric8) are outdated.

![screen shot 2018-01-12 at 15 37 44](https://user-images.githubusercontent.com/156692/34862595-a293c510-f7ae-11e7-9f2f-4524dda9f058.png)

**Comment by abkieling** [comment]
I wonder if we should move these instructions to Help and provide a link from the Connect page.

**Comment by tadayosi** [comment]
Ah, sounds like a plan. I like it. Let's go with it.

But then there's another consideration. If we link some plugin tab pages to their respective help sections, then shouldn't we consider a uniform design to link a page to its respective help (if it exists)?

**Comment by abkieling** [comment]
Unfortunately, we cannot link to a specific help page because we don't register a route for each one.
It might be better to contact the UX team and ask about best practices around help pages.

**Comment by tadayosi** [comment]
OK, let's just focus on updating the text here. An issue at hawtio-core should follow it to make help pages linkable.

**Comment by tadayosi** [comment]
See also hawtio/hawtio-core#18

**Comment by abkieling** [comment]
I updated the instructions.
https://github.com/hawtio/hawtio-jmx/commit/4ec6d9c97e7f6cacc8e16045d0fb5bc7f295ddce
