### ISSUE TITLE
More intuitive feedback on connecting to other JVM

### ISSUE THREAD

**Issue by skarsaune** [hawtio/hawtio-jmx#41]
Maybe some responsibility falls on hawtio-core or other components, in that case please split the issue as you see fit (if the request seems sensible).

1. Is it possible to show the PID in the page title like in 1.5 ? I think that would be very valuable. Additionally there used to be some preference to use different color labels for different connection patterns? I got the impression that it was never in fact completely implemented, but I think the idea was quite promising. Does anyone know why it was dropped and if its worth picking up?
1. When connecting to a local/discovered process and this for some reason fails, the new tab is then actually connected to the original Java process, and no warning is given. This can cause confusion. Is it possible to detect this situation give and error message and close the new tab immediately, so that the user does not get confused and waste time introspecting the wrong process?
1. Alternatively I could port the runtime plugin from 1.x and we could open that path by default on these ad hoc connections. That would immediately show the PID, uptime, host and other information helpful in verifying that the connection is indeed to the intended destination.

**Comment by abkieling** [comment]
@gashcrumb can you provide some info about the features mentioned above?

**Comment by abkieling** [comment]
@skarsaune About items 1 and 3, I haven't done much work on hawtio v1 and would need to find and understand the code that adds the PID to the page title. Then, we can decide if it's better to reimplement or port the existing code. This issue could be about that.
About item 2, please create a new GitHub issue for it and provide as many details as possible, including steps to reproduce it.
What do you think?
