### ISSUE TITLE
Error callback is always ignored in JolokiaService

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-jmx#45]
I've been testing some functionality over in the hawtio-integration project, and I expected to see some error messages being displayed when Jolokia returns an error response. However, this never happens.

I think the syntax defining the success / error callbacks is wrong in each of the JolokiaService methods.  E.g we have:

```
      return this.$q((resolve, reject) => {
        this.jolokia.request(
          { type: 'read', mbean: mbean, attribute: attribute },
          { success: response => resolve(response.value) },
          { error: response => {
              log.error(`JolokiaService.getAttribute('${mbean}', '${attribute}') failed. Error: ${response.error}`);
              reject(response.error);
            }
          });
      });
```

The success and error callbacks are within separate objects. I think they should be part of the same object, else the error option will get ignored.

**Comment by tadayosi** [comment]
I think so, too. In addition, originally we've used `Core.onSuccess(...)` helper function when invoking Jolokia to make sure we get a uniform error handling throughout the codebase. Unless there's any strong objection against using `Core.onSuccess(...)` we should continue to use it here in `JolokiaService` as well.

**Comment by abkieling** [comment]
@jamesnetherton You are right. The error function should be in the same object as the success function. 

Should we define a function for ajaxError as well?

If we use Core.onSuccess(), we'll need to still implement the error function to be able to reject the promise, right?

**Comment by jamesnetherton** [comment]
@akieling Yes, even with `Core.onSuccess()` we still need to implement the error function. I have a local change that does this, so I can commit it shortly.
