### ISSUE TITLE
Connect options token is not used anymore

### ISSUE THREAD

**Issue by astefanutti** [hawtio/hawtio-jmx#47]
It breaks hawtio-online integration. Seems related to e9377fd585f0eb6fa3a2a72883db62a5be0dee70.

@tadayosi what's the target integration you recommend? Should that be articulated with the `Core.AuthService`?

**Comment by astefanutti** [comment]
I've reverted the logic back in 85bcf09ce3c14284de985b1341c9b188eb6fcaaa. Let me know if that's an issue.

**Comment by tadayosi** [comment]
@astefanutti Oops, sorry!  Yes, `AuthService` has the `token` field which you may probably use for that purpose, but atm I don't have strong opinions about whether it should be in `AuthService` or `ConnectOptions`. At least, if hawtio-online requires `token` on `ConnectOptions`, should it be declared on the `ConnectOptions` interface so that we can see it's not ephemeral?

**Comment by abkieling** [comment]
@astefanutti @tadayosi where do you think is the best place to store the authentication tokens: local storage, session storage, cookies, etc.?
ConnectOptions is stored in local storage and I think AuthService exists only in memory.
I've seen many blog posts suggesting that authentication tokens should be stored in local storage but I've also seen people saying that's not very secure. Maybe using session storage is a good compromise. What do you think?

**Comment by astefanutti** [comment]
@tadayosi `ConnectOptions` token is used by the existing OpenShift JVM console and the new Hawtio OpenShift console.

@akieling my understanding is that it's acceptable to store token in the local storage depending on their expiration. With the current integration, session storage is not an option as token is shared between the OpenShift console / Hawtio console and the JVM console windows. Besides, it would requires the user to authenticate each time he / she opens the application.

**Comment by astefanutti** [comment]
One option that I see to remove the `ConnectOptions` token would be to used hawtio-oauth instead as this is done in hawtio 2.x with @tadayosi work.
