### ISSUE TITLE
JMX Plugin - Invoke JMX operation shows result in tiny window

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-jmx#5]
On the java lang threading mbean, there is a thread info operation you can get details for thread id 1, and then it returns 

![screen shot 2015-05-27 at 7 52 32 am](https://cloud.githubusercontent.com/assets/477100/7829634/c644dc3e-0444-11e5-8f2e-a5e574fd3c4f.png)

And after manually resizing the window you can see the details

![screen shot 2015-05-27 at 7 53 29 am](https://cloud.githubusercontent.com/assets/477100/7829641/d7763566-0444-11e5-871e-138645d1f85e.png)

**Comment by gashcrumb** [comment]
Seems like the codemirror widget isn't showing up properly when initially rendered, will take a look

**Comment by davsclaus** [comment]
thanks, btw this UI could use a bit of love to make it nicer looking.

For example the jolokia uri path could be hidden by default, and then some kind of expander or button or something to show it.

**Comment by gashcrumb** [comment]
Yeah, I wonder if the URL path is really even valid for any JMX operation that requires arguments to be honest.

**Comment by gashcrumb** [comment]
Let's open a new issue to tidy up the operation page.  I think we can switch it to the forms2 plugin, add some text and perhaps move the action buttons underneath the form so there's a better page flow perhaps?
