### ISSUE TITLE
Replace remote connection login dialog box with a full page

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-jmx#51]
When connecting to a remote endpoint that requires username/password authentication, show a full login page instead of the currently shown dialog box.

**Comment by tadayosi** [comment]
Interesting. What's the motivation and expected benefits behind this?

**Comment by abkieling** [comment]
I think showing a login page to authenticate users when connecting to remote servers would improve consistency. Also, it would be important to only start the Jolokia pooling or make any other request to Jolokia after the user is logged in. Currently, the app is initialized before the user authenticates with the remote server. This issue has already been fixed for the login page in the master branch.
Do you think it would be good to reuse the login page for remote connections?

**Comment by tadayosi** [comment]
I don't have a strong opinion on it actually. If it solves some technical problems then definitely we should do that. One concern is that IIUC the PatternFly login page requires a different html page like:

    <html class="login-pf">
    ...

so it may introduce a complicated redirect flow to hawtio-jmx. When I worked on the Hawtio login page I found redirecting from the login page to the main page cumbersome to implement.

**Comment by abkieling** [comment]
Fair enough. It might be better to do some investigation to check it doesn't complicate things.

**Comment by skarsaune** [comment]
Be aware that Remote and Discover connect tabs have a pretty complicated way of doing it today, including saving credentials to local storage and picking it up in the new tab based on connection name. So the current scheme requires more than just a visual change I think. Can see when I get the time to give a better account.

**Comment by abkieling** [comment]
Yep, that code is complicated and it's risky to change it. I'll close this issue to avoid creating problems.
