### ISSUE TITLE
jmx-plugin - tidy up JMX operation page

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-jmx#6]
The JMX operation page could use a bit of layout work.  Perhaps some descriptive text for starters explaining what the page does, maybe improve the list layout of the operations, etc.

Also the buttons that do stuff (execute, reset etc) for the form should maybe go underneath the form.  And the "Back" button could maybe just be a list icon.

**Comment by gashcrumb** [comment]
@davsclaus, have worked over this page a bit, would love some feedback...

**Comment by davsclaus** [comment]
super work @gashcrumb
