### ISSUE TITLE
jmx-plugin - Tidy up JMX attribute dialog

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-jmx#7]
The layout of this dialog could use some work, might just be a matter of switching it to the form2 plugin.  Also perhaps using hawtio-editor instead of the textarea for any json that shows up would be good.

**Comment by gashcrumb** [comment]
@davsclaus wouldn't mind some feedback on this change also, switched this dialog to hawtio-form-2 and reworked it a bit so the value is show via hawtio-editor, so big values are easier to look at.

**Comment by davsclaus** [comment]
When I run hawtio-jmx locally with gulp, then I get javascript errors and the page cannot load

I did

git pull --rebase
bower update --force
gulp

And then open localhost:2772

![screen shot 2015-05-28 at 9 54 22 am](https://cloud.githubusercontent.com/assets/477100/7855046/dd27bd42-051e-11e5-8bb3-7d4681c4c3ef.png)

**Comment by davsclaus** [comment]
I found this in jolokia 1.1 js

error proxying to "http://localhost:8282/hawtio/jolokia/": Error: connect ECONNREFUSED

I do not have any ENV setup that uses 8282 etc

davsclaus:~/workspace/hawtio-jmx (master)/$ export | grep 8282
davsclaus:~/workspace/hawtio-jmx (master)/$

**Comment by gashcrumb** [comment]
Have you tried clearing your local storage by any chance?

**Comment by davsclaus** [comment]
Yes its still the same problem. I havent found a nice ui in chrome so I clear from the js console

```
window.localStorage.clear();
undefined
window.localStorage.length
0
Navigated to http://localhost:2772/
jquery.js:8630 GET http://localhost:2772/jolokia 500 (Internal Server Error)jQuery.ajaxTransport.send @ jquery.js:8630jQuery.extend.ajax @ jquery.js:8166checkNext @ hawtio-jmx.js:4673(anonymous function) @ hawtio-jmx.js:4702self.loadPlugins.executeTask @ hawtio-core.js:348self.loadPlugins.bootstrap @ hawtio-core.js:353self.loadPlugins.loadScripts @ hawtio-core.js:400self.loadPlugins @ hawtio-core.js:405(anonymous function) @ hawtio-core.js:651jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
jquery.js:8630 GET http://localhost:2772/jolokia 500 (Internal Server Error)jQuery.ajaxTransport.send @ jquery.js:8630jQuery.extend.ajax @ jquery.js:8166checkNext @ hawtio-jmx.js:4673maybeCheckNext @ hawtio-jmx.js:4668(anonymous function) @ hawtio-jmx.js:4698jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211done @ jquery.js:8266jQuery.ajaxTransport.send.callback @ jquery.js:8605
angular.js:4167 Uncaught TypeError: Cannot read property 'hostname' of null
```

**Comment by gashcrumb** [comment]
So when running 'gulp' the gulpfile sets up a proxy for /jolokia, it's set up out of the box to hit an instance started from "hawtio-web" in the hawtio 1.x branch via "mvn exec java -DstartLR=false".

Let me see if I can tidy up that error a bit now that I can see what's going on :-)  Was just going to post that I haven't been able to reproduce it...

**Comment by davsclaus** [comment]
Ah yeah I found the port 8282 which was hardcoded in the gulp settings file. So I kind though that that a Java JVM was needed to run along side. 

Though I recall using hawtio-jmx in the past without having a JVM running.

**Comment by gashcrumb** [comment]
Yeah, you should be able to and then use the connect dialog...  about to push a fix for it + some improved logging.  BTW, the local storage reset button is back in the preferences.

**Comment by gashcrumb** [comment]
@davsclaus should be better now...

**Comment by gashcrumb** [comment]
Hm, should probably not bother showing a jolokia url for any ObjectName attribute, those are calculated locally.

**Comment by davsclaus** [comment]
+1 to not show the jolokia url - its more of a distraction for the end users / and maybe also a bit confusing for some users what it is.

**Comment by davsclaus** [comment]
@gashcrumb this looks much better.
