### ISSUE TITLE
index.html has no closing meta tag

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-jmx#8]
This tag has no closing tag
https://github.com/hawtio/hawtio-jmx/blob/master/index.html#L7

I assume it should just be <meta ... />

And it would be the same fix in the other hawtio modules?

@gashcrumb - would that be right?

**Comment by gashcrumb** [comment]
Closing tag isn't required there.  In html closing tags are optional for a
lot of elements,  unlike xml.

**Comment by davsclaus** [comment]
Okay if it does not hurt then its maybe nice to add em as I see validation errors in various web browsers such as firefox etc.

**Comment by gashcrumb** [comment]
Yeah, wouldn't hurt.  A nice list of tags that are okay to have self-closing -> http://xahlee.info/js/html5_non-closing_tag.html
